include:
  - path:
      - postgres.yml

services:
  python-app:
    container_name: pythonBot
    build:
      context: .
      dockerfile: ./moddingway/Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      MOD_LOGGING_CHANNEL_ID: ${MOD_LOGGING_CHANNEL_ID}
      NOTIFY_CHANNEL_ID: ${NOTIFY_CHANNEL_ID}
      DEBUG: ${DEBUG}
      MODDINGWAY_ENVIRONMENT: ${MODDINGWAY_ENVIRONMENT}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      INACTIVE_FORUM_CHANNEL_ID: ${INACTIVE_FORUM_CHANNEL_ID}
      INACTIVE_FORUM_DURATION: ${INACTIVE_FORUM_DURATION}
      PTC_EVENT_FORUM_ID: ${PTC_EVENT_FORUM_ID}
      PTC_EVENT_FORUM_DURATION: ${PTC_EVENT_FORUM_DURATION}
      EVENT_BOT_ID : ${EVENT_BOT_ID}
      EVENT_WARN_CHANNEL: ${EVENT_WARN_CHANNEL}
  python-app-local:
    extends:
      service: python-app
    environment:
      POSTGRES_HOST: postgres_local
    depends_on:
      postgres_local:
        condition: service_healthy
