include:
  - path:
      - postgres.yml

services:
  python-app:
    container_name: pythonBot
    build:
      context: .
      dockerfile: ./src/Dockerfile
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GUILD_ID: ${GUILD_ID}
      MOD_LOGGING_CHANNEL_ID: ${MOD_LOGGING_CHANNEL_ID}

  python-app-local:
    extends:
      service: python-app
    environment:
      POSTGRES_HOST: postgres_local
    depends_on:
      postgres_local:
        condition: service_healthy
