services:
  postgres_local:
    container_name: postgres_db
    build:
      context: .
      dockerfile: ./docker/Postgres.Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=moddingway
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}