include:
  - path: 
      - docker-compose.yml
      - postgres.override.yml
services:
  postgres_local:
    container_name: postgres_db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB:-moddingway}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-moddingway} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
